document.write(' <footer class="grid_container_footer">');
document.write('');
document.write('    <div class="footer_0">');
document.write('        <img src="./image/logo_nb.png" alt="Italian Trulli">');
document.write('    </div>');
document.write('  ');
document.write('      <div class="footer_1">');
document.write('        <h4>Telefon:</h4>');
document.write('            <p><a href="tel:+4798281233" target="_blank">98 28 12 33</a></p>');
document.write('      </div>');
document.write('  ');
document.write('      <div class="footer_2">');
document.write('        <h4>E-post:</h4>');
document.write('            <p><a href="mailto:post@bergbjorgum.no" target="_blank">post@bergbjorgum.no</a></p>');
document.write('      </div>');
document.write('  ');
document.write('      <div class="footer_3">');
document.write('        <h4>Adresse:</h4>');
document.write('            <p>Melhusvegen 161, 7224 Melhus</p>');
document.write('      </div>');
document.write('  ');
document.write('  </footer>');
document.write('  <footer>');
document.write('    <div class="footer_4">');
document.write('      <p>Copyright © ');
document.write('        <script>document.write(new Date().getFullYear())</script>');
document.write('      </p>');
document.write('      </div>');
document.write('  </footer>');
